noun1 = game.ask_for_string("i need a noun")
verb1 = game.ask_for_string("now a verb")
noun2 = game.ask_for_string("another noun")
noun3 = game.ask_for_string("3rd noun")
verb2 = game.ask_for_string("another verb")
exc = game.ask_for_string("give me an exclamation")
game.splash("let the story begin!")
game.splash ("one day there was a " + noun1)
game.splash ("it started to " + verb1)
game.splash("later it saw two things. a " + noun2)
game.splash("and a " + noun3)
game.splash("they became its friends.")
game.splash("they did everything together including " + verb2 + "together!")
game.splash("whenever they left eachother, they would do their thing that they called their friendly yell")
game.splash("they would always look to the sky and yell, " + exc)
game.set_game_over_message(True, "THE END!")
game.game_over(True)